### ISSUE TITLE
peerDeps don't cover latest ember-template-lint or prettier versions

### ISSUE THREAD

**Issue by elwayman02** [ember-template-lint/ember-template-lint-plugin-prettier#155]
https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/blob/master/package.json#L31-L32

The peerDep range excludes support for `ember-template-lint` v3+ and `prettier` v2+, which throws warnings when consumed by projects using those versions:

`warning " > ember-template-lint-plugin-prettier@2.0.1" has unmet peer dependency "ember-template-lint@>=2.10.0".`

Unless this plugin is meant to specifically *not* support those versions, can we update the peerDeps to be inclusive of the latest releases?

**Comment by dcyriller** [comment]
Thanks for the report @elwayman02!
Have you had the chance to see https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/pull/150?
I think the problem you're describing is fixed by this PR and released in 2.0.1.

**Comment by elwayman02** [comment]
@dcyriller unfortunately, as you can see from the example I gave above, we are using v2.0.1 already and still seeing the peer dependency warnings (when using the latest versions of ember-template-lint and prettier). That said, it's possible that this is a bug in the dependency checker that creates the warnings - I'll try to narrow that down and get back to you.

**Comment by elwayman02** [comment]
So, I've just learned that these warnings come from yarn itself, which is a bit concerning. When the change in #150 landed, were you able to confirm in another project using the latest deps that it was working as expected?

**Comment by elwayman02** [comment]
Going to close this, as I think this is just an issue with the way yarn handles peerDeps, and not something that can be fixed (and certainly not by making a change to this project).

**Comment by dcyriller** [comment]
> When the change in #150 landed, were you able to confirm in another project using the latest deps that it was working as expected

I tested the changes with both npm and yarn.
Do you happen to use yarn workspaces? In that case, I saw issue 5810 in https://github.com/yarnpkg/yarn? (I don't want to cross link as I'm unsure it is the root cause.)
