### ISSUE TITLE
Not compatible with ember-template-lint v4

### ISSUE THREAD

**Issue by runspired** [ember-template-lint/ember-template-lint-plugin-prettier#195]
Use of version 3.0.1 results in:

```
(node:76359) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/lib/index.js
require() of ES modules is not supported.
require() of /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/lib/index.js from /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint-plugin-prettier/lib/rules/prettier.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/runspired/github/private/fnb/frontend/node_modules/ember-template-lint/package.json.
```

Also opened https://github.com/ember-template-lint/ember-template-lint/issues/2320

**Comment by dcyriller** [comment]
I just released a v4. It should be resolved by now!

**Comment by charlesfries** [comment]
Anyone else still seeing a similar error even after updating both packages?

```
(node:17112) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js
require() of ES modules is not supported.
require() of C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js from C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-template-lint\lib\get-config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope 
as ES modules.
Instead rename ember-template-lint-plugin-prettier.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-template-lint-plugin-prettier\package.json.
```

```
"ember-cli": "~4.1.0",
"ember-source": "~3.28.8",
"ember-template-lint": "^4.0.0",
"ember-template-lint-plugin-prettier": "^4.0.0",
```
